'use client'
import Link from 'next/link'
import { useLang } from '@/contexts/LangContext'

export default function PrivacyPage() {
  const { lang } = useLang()
  const isKo = lang === 'ko'

  return (
    <div className="max-w-2xl mx-auto px-4 py-10">
      <Link href="/" className="text-slate-500 hover:text-indigo-400 text-sm transition-colors">
        {isKo ? '← 홈으로' : '← Back to Home'}
      </Link>

      <div className="mt-8 mb-10">
        <div className="w-10 h-10 bg-indigo-500/20 rounded-xl flex items-center justify-center text-xl mb-4">🔒</div>
        <h1 className="text-3xl font-bold mb-2">{isKo ? '개인정보 처리방침' : 'Privacy Policy'}</h1>
        <p className="text-slate-500 text-sm">{isKo ? '최종 업데이트: 2026년 6월 22일' : 'Last updated: June 22, 2026'}</p>
      </div>

      <div className="space-y-8 text-slate-300 leading-relaxed">

        {/* 핵심 요약 */}
        <div className="bg-emerald-500/10 border border-emerald-500/20 rounded-2xl p-6">
          <h2 className="text-emerald-400 font-semibold text-lg mb-3">
            {isKo ? '한 줄 요약' : 'TL;DR'}
          </h2>
          <p className="text-emerald-300">
            {isKo
              ? 'ToolNest의 모든 도구는 100% 브라우저에서 실행됩니다. 입력한 데이터는 서버로 전송되지 않으며, 저장·수집·공유되지 않습니다.'
              : 'All ToolNest tools run 100% in your browser. Your input is never sent to, stored on, or shared with any server.'}
          </p>
        </div>

        <section>
          <h2 className="text-white font-semibold text-xl mb-3">
            {isKo ? '1. 수집하는 정보' : '1. Information We Collect'}
          </h2>
          <p>
            {isKo
              ? 'ToolNest는 어떠한 개인정보도 수집하지 않습니다. 비밀번호, 아이디, IP 주소 등 도구에 입력하거나 생성되는 모든 데이터는 귀하의 브라우저 내에서만 처리됩니다.'
              : 'ToolNest does not collect any personal information. Passwords, IDs, IP addresses, and all other data entered into or generated by our tools are processed exclusively within your browser.'}
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold text-xl mb-3">
            {isKo ? '2. 브라우저 내 처리 방식' : '2. How Browser-Only Processing Works'}
          </h2>
          <p className="mb-3">
            {isKo
              ? '모든 도구는 JavaScript로 작성되어 귀하의 기기(브라우저)에서 직접 실행됩니다:'
              : 'All tools are written in JavaScript and execute directly on your device (browser):'}
          </p>
          <ul className="space-y-2 list-none">
            {(isKo ? [
              '비밀번호 생성기 — 브라우저의 crypto.getRandomValues() API로 생성, 서버 통신 없음',
              '아이디 생성기 — 단어 조합 및 UUID 생성이 로컬에서 처리됨',
              '서브넷 계산기 — IP 계산은 전적으로 브라우저에서 수행됨',
            ] : [
              'Password Generator — uses browser\'s crypto.getRandomValues() API; no server communication',
              'ID Generator — word combination and UUID generation happen locally',
              'Subnet Calculator — all IP calculations are performed entirely in the browser',
            ]).map((item, i) => (
              <li key={i} className="flex items-start gap-2.5 text-slate-400">
                <span className="text-emerald-400 mt-0.5 shrink-0">✓</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-white font-semibold text-xl mb-3">
            {isKo ? '3. 쿠키 및 트래킹' : '3. Cookies & Tracking'}
          </h2>
          <p>
            {isKo
              ? 'ToolNest는 언어 설정과 쿠키 동의 선택을 로컬 스토리지에 저장합니다. 동의한 경우에만 Google Analytics와 AdSense가 이용 통계 및 광고 제공을 위한 쿠키를 사용할 수 있습니다.'
              : 'ToolNest stores your language preference and cookie-consent choice in localStorage. Only after you consent, Google Analytics and AdSense may use cookies for traffic measurement and ad delivery.'}
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold text-xl mb-3">
            {isKo ? '4. 제3자 서비스' : '4. Third-Party Services'}
          </h2>
          <p>
            {isKo
              ? '사이트는 Vercel을 통해 호스팅되며, 동의한 경우 Google Analytics와 Google AdSense를 사용합니다. 각 서비스는 자체 개인정보 처리방침에 따라 접속 정보와 이용 데이터를 처리할 수 있습니다. 도구에 입력한 내용은 이들 서비스로 전송하지 않습니다.'
              : 'This site is hosted by Vercel and, with your consent, uses Google Analytics and Google AdSense. These services may process access and usage data under their own privacy policies. Data entered into the tools is not sent to these services.'}
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold text-xl mb-3">
            {isKo ? '5. 문의' : '5. Contact'}
          </h2>
          <p>
            {isKo
              ? '개인정보 처리방침에 관한 문의사항이 있으시면 GitHub 저장소를 통해 이슈를 남겨주세요.'
              : 'For questions about this privacy policy, please open an issue on the GitHub repository.'}
          </p>
        </section>

      </div>
    </div>
  )
}
